### ISSUE TITLE
Gracefully shutdown from command line

### ISSUE THREAD

**Issue by gfgit** [traintastic/traintastic#10]
**Describe the bug**
When not running with `--tray` there is now elegant way to close the server CMD window.
`CTRL-C` and `CTRL-Z` do not work.
Maybe add [control-handler-function](https://learn.microsoft.com/en-us/windows/console/registering-a-control-handler-function) (Windows specific).
Or catch `SIGINT or SIGTERM`signal (Unix specific, may work on Windows too)
Or maybe add both.
Crashing at shutdown prevents auto-saving.

**Comment by reinder** [comment]
Good suggestion, I didn't now about that function yet. Thanks!

**Comment by gfgit** [comment]
[Boost.Asio](https://www.boost.org/doc/libs/1_81_0/doc/html/boost_asio/overview/signals.html)  seems to already support this and is cross platform.
