### ISSUE TITLE
Add wizard for easy interface setup

### ISSUE THREAD

**Issue by reinder** [traintastic/traintastic#107]
The setup of an interface/command station can be a bit difficult, a wizard can help the user to go to the process step by step making it easy to setup.

**Comment by reinder** [comment]
Preview: https://youtu.be/2gYl7zVnHGo

**Comment by reinder** [comment]
@gfgit Tried the wizard in Italian now that is available (many thanks!)...can't read it but just to see if everything works as it should.

![image](https://github.com/traintastic/traintastic/assets/886282/e069893c-8e15-4ae9-81c0-0e43b1dcfbc4)

- Red: Menu and text are different, I think we should change it to use `$xxx$` so it reuses the exact values as used in the menu to make sure it matches (or is it different for a reason?)
-  Yellow: the buttons are English, I need to set custom labels so Traintastic's translation system works.

**Comment by gfgit** [comment]
> * Red: Menu and text are different, I think we should change it to use `$xxx$` so it reuses the exact values as used in the menu to make sure it matches (or is it different for a reason?)

Hi, it's my mistake. While translating I was thinking about something similar to $xxx$.
Also I've noticed there are many duplicated strings in different contexts, like the string "Command station". Some of them might actually translate to different words in some language but others are clearly duplicates.

> * Yellow: the buttons are English, I need to set custom labels so Traintastic's translation system works.

Originally I thought you used standard Qt translation system for default buttons.
I will add the new strings.

Also I might try experimenting a `*.json` to `*.ts` sort of thing so I can edit translations inside Qt Linguist. Or at least some GUI which can make work easier
