### ISSUE TITLE
Signal/Turnout infinite loop

### ISSUE THREAD

**Issue by gfgit** [traintastic/traintastic#116]
**Describe the bug**
Hi, this is not a real bug but more a speculation.
Now that PR #113 implements Signal Aspect re-evaluation and turnout "locking" when reserved, some rare configurations could possibly cause infinite recursions.
This is really rare and can be interrupted by "Disconnecting" from command station, remove path reservation and reconnect.
However a more robust solution would be:

1. External output change detected
2. We match a signal aspect different from the current value
3. Re-evaluate SignalPath logic
4. Trigger signal aspect change, send to command station
5. Command station *should* reply with the new state (depending on protocol used) and everything is fine
6. BUT, if command station keeps replying wrong (other) output state, reevaluation is triggered over and over.
7. Put a **retry limit** which is reset every minute to extinguish infinite loop possibility

What you think about this?

**Comment by gfgit** [comment]
You can experiment Z21 in simulation mode and altering it's `SimulationIOHandler` to always reply to changes with a fixed output state regardless of the one requested.
Being really rare we could just ignore this and skip it but I think it would not cost us much to put a retry limit and maybe tell user with error message that command station is not behaving properly

**Comment by reinder** [comment]
I agree, we should add a retry limit, I'd say 3 would be enough and the indeed report an error. Apart from the command station not behaving properly, there could also be other things e.g. via LocoNet control the accessory.

But what to do next?
- Should we stop the whole world?
- If the turnout is in an active path, should we EStop the train?
- There is no real danger in a wrong signal aspect being displayed (unless there is a ABC connected).

**Comment by gfgit** [comment]
Implemented in #115
