### ISSUE TITLE
Client warning: QObject::connect(Event, Unknown): invalid nullptr parameter

### ISSUE THREAD

**Issue by gfgit** [traintastic/traintastic#130]
File: `outputkeyboard.cpp` line 97 at commit 55503980
Event `m_outputUsedChanged` is nullptr which triggers a Qt warning:
`qt.core.qobject.connect: QObject::connect(Event, Unknown): invalid nullptr parameter`

**Comment by reinder** [comment]
Good catch, that event doesn't exist on the server anymore, due to #95. I'll look into re-adding the used output functionality.
