### ISSUE TITLE
Current SERVER build error on macOS 14.3.1

### ISSUE THREAD

**Issue by DrEVILish** [traintastic/traintastic#132]
```
$> cmake ../ -DCMAKE_BUILD_TYPE=Release
-- TRAINTASTIC_VERSION_EXTRA=-dev
-- DEBIAN_PACKAGE_VERSION_EXTRA=
-- The C compiler identification is AppleClang 15.0.0.15000309
-- The CXX compiler identification is AppleClang 15.0.0.15000309
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Python3: /opt/homebrew/Frameworks/Python.framework/Versions/3.12/bin/python3.12 (found version "3.12.3") found components: Interpreter
-- Found ZLIB: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/lib/libz.tbd (found version "1.2.12")
-- Found Doxygen: /opt/homebrew/bin/doxygen (found version "1.11.0") found components: doxygen missing components: dot mscgen dia
-- Configuring done (0.7s)
-- Generating done (0.1s)
-- Build files have been written to: /Users/drevilish/traintastic/server/build
```

```
$> cmake --build . --config Release --target traintastic-server
[  0%] Updating language files
[  0%] Built target traintastic-lang
[  0%] Building CXX object CMakeFiles/traintastic-server.dir/src/main.cpp.o
In file included from /Users/drevilish/traintastic/server/src/main.cpp:25:
In file included from /Users/drevilish/traintastic/server/src/options.hpp:26:
In file included from /Users/drevilish/traintastic/server/thirdparty/boost/boost/program_options.hpp:15:
In file included from /Users/drevilish/traintastic/server/thirdparty/boost/boost/program_options/options_description.hpp:13:
In file included from /Users/drevilish/traintastic/server/thirdparty/boost/boost/program_options/value_semantic.hpp:12:
In file included from /Users/drevilish/traintastic/server/thirdparty/boost/boost/any.hpp:20:
In file included from /Users/drevilish/traintastic/server/thirdparty/boost/boost/type_index.hpp:29:
In file included from /Users/drevilish/traintastic/server/thirdparty/boost/boost/type_index/stl_type_index.hpp:47:
/Users/drevilish/traintastic/server/thirdparty/boost/boost/container_hash/hash.hpp:130:33: error: no template named 'unary_function' in namespace 'std'; did you mean '__unary_function'?
        struct hash_base : std::unary_function<T, std::size_t> {};
                           ~~~~~^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/include/c++/v1/__functional/unary_function.h:46:1: note: '__unary_function' declared here
using __unary_function = __unary_function_keep_layout_base<_Arg, _Result>;
^
1 error generated.
make[3]: *** [CMakeFiles/traintastic-server.dir/src/main.cpp.o] Error 1
make[2]: *** [CMakeFiles/traintastic-server.dir/all] Error 2
make[1]: *** [CMakeFiles/traintastic-server.dir/rule] Error 2
make: *** [traintastic-server] Error 2
```

All tools were installed with "homebrew" brew

**What's happening**
unary_function and binary_function are no longer provided in C++17 and newer Standard modes. They can be re-enabled with _LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY_FUNCTION.
[release note xcode 15](https://developer.apple.com/documentation/xcode-release-notes/xcode-15-release-notes)
 **What must be done**
all library must update their code to use `std::function` & `std::bind` instead of `unary_function`
**Workaround**
- Select Pods > Build Settings > In section Apple Clang - Preprocessing > under Macro section 
- add in release & debug `_LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY_FUNCTION`

_Originally posted by @Armanoide in https://github.com/facebook/react-native/issues/37748#issuecomment-1580334650_

**Comment by reinder** [comment]
Hi Ryan,

Thanks for the feedback, the main reason the builds are for Ubuntu is that GitHub action has Ubuntu runners instead of Debian runners. I'd expect it will built on Debian to, probably the build instructions also apply to Debian.

Reinder

**Comment by reinder** [comment]
Hi Ryan,

Thanks for the report, I don't have a macOS system available, can you verify if it will built with the mentioned define set? (As temporary fix, the real fix is updating boost I'd expect.)

Reinder

**Comment by DrEVILish** [comment]
Adding -> to CMakeLists.txt
```
if(APPLE)
  set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Werror=partial-availability -Werror=unguarded-availability -Werror=unguarded-availability-new -D_LIBCPP_EN$
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Werror=partial-availability -Werror=unguarded-availability -Werror=unguarded-availability-new -D_LIBCP$
endif()
```

I now have an issue with lua.hpp missing, something to do with the way macOS or homebrew links it's libraries now.
Need to get the build process to pull from `/opt/homebrew/include/lua` normally.

**Comment by reinder** [comment]
Currently the Lua paths are hardcoded for macOS, but that no longer works.

Best solution I think is remove:
```
elseif(APPLE)
  set(LUA_INCLUDE_DIR "/usr/local/opt/lua@5.3/include/lua")
  set(LUA_LIBRARIES "/usr/local/opt/lua@5.3/lib/liblua5.3.dylib")
```

Then `FindPackage` will be used for macOS too, so `FindLua.cmake` needs to be modified to support macOS.

Where are `lua.hpp` and the library located in your homebrew folder and what is the name of the library file?

**Comment by DrEVILish** [comment]
Working
Debian server build: localhost only: false
macOS client build: 
Got a random seg fault on server when trying to add DCC-EX. I then recreated the world but haven't been able to reproduce.

**Comment by reinder** [comment]
Just added a `macos-13` build in GitHub Actions, it has the same `unary_function` issue, but no issue with finding Lua, that seems to be a macOS 14 thing.

see: https://github.com/traintastic/traintastic/pull/136

**Comment by reinder** [comment]
> Adding -> to CMakeLists.txt
> 
> ```
> if(APPLE)
>   set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Werror=partial-availability -Werror=unguarded-availability -Werror=unguarded-availability-new -D_LIBCPP_EN$
>   set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Werror=partial-availability -Werror=unguarded-availability -Werror=unguarded-availability-new -D_LIBCP$
> endif()
> ```
> 

Are those `-Werror=...` options required for macOS 14?

**Comment by DrEVILish** [comment]
No not required, builds fine with just ->
```
if(APPLE)
  set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -D_LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY_FUNCTION")
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D_LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY_FUNCTION")
endif()
```

**Comment by reinder** [comment]
Lua is still an issue on apple silicon right? (or is that resolved too?)
