### ISSUE TITLE
DCC-EX / RedHat++ LocoNet LBServer and TCP binary

### ISSUE THREAD

**Issue by DrEVILish** [traintastic/traintastic#141]
Unable to connect to RedHat++ LocoNet LBServer 

This happens on both macOS -server and debian -server

Tried with multiple ports.

Verified it's not a IoTT/RedHat++ issue as JMRI from the same computer (macOS) can connect and run trains.

```
/opt/traintastic$ ./traintastic-server 
2024-06-18 03:35:30.181682 traintastic I1001: Traintastic v0.3.0-dev
2024-06-18 03:35:30.182555 traintastic I1006: boost 1.74.0
2024-06-18 03:35:30.182568 traintastic I1007: nlohmann::json 3.10.5
2024-06-18 03:35:30.184749 traintastic I1008: libarchive 3.6.2 zlib/1.2.13 liblzma/5.4.1 bz2lib/1.0.8 liblz4/1.9.4 libzstd/1.5.4
2024-06-18 03:35:30.184779 traintastic I1009: zlib 1.2.13
2024-06-18 03:35:30.184787 traintastic I9002: Lua 5.3.6  Copyright (C) 1994-2020 Lua.org, PUC-Rio
2024-06-18 03:35:30.184845 settings N1008: Loaded settings
2024-06-18 03:35:30.185108 traintastic I1005: Building world index
2024-06-18 03:35:30.192403 server N1005: Discovery enabled
2024-06-18 03:35:30.192444 server N1007: Listening at 0.0.0.0:5740
2024-06-18 03:36:01.623666 connection[192.168.20.57:54145] I1003: New connection
2024-06-18 03:36:03.316943 traintastic N1002: Created new world
2024-06-18 03:36:03.316981 world N1010: Edit mode: enabled
2024-06-18 03:36:15.994546 world N1012: Communication: enabled
2024-06-18 03:36:17.568334 world N1013: Communication: disabled
2024-06-18 03:36:40.111099 world N1012: Communication: enabled
2024-06-18 03:36:40.208353 loconet_1 E2007: Socket write failed (Success)
2024-06-18 03:36:42.560187 world N1014: Power: on
2024-06-18 03:36:43.861528 world N1015: Power: off
2024-06-18 03:36:44.396010 world N1014: Power: on
2024-06-18 03:36:44.995172 world N1013: Communication: disabled
2024-06-18 03:36:45.362276 world N1012: Communication: enabled
2024-06-18 03:36:45.428771 loconet_1 E2007: Socket write failed (Success)
```

Created a brand new world, added Interface, Loconet, try to connect Fails.

**Comment by reinder** [comment]
@DrEVILish thanks for the log, `2024-06-18 03:36:45.428771 loconet_1 E2007: Socket write failed (Success)` was very helpful, the "error" was "Success", there was a success check missing.

Can you verify if this resolved it? (latest `master`)

**Comment by DrEVILish** [comment]
This has fixed the issue for initiating the first connection.

macOS Server:
However if I close the connection using the "toggle connection" button, it shows as `2024-06-19 06:55:47.839898 world N1013: Communication: disabled` then crashes. Client UI still shows LocoNet as "Online"

I have to force quit the server.

<img width="848" alt="Screenshot 2024-06-19 at 06 56 13" src="https://github.com/traintastic/traintastic/assets/6287003/ab3a05fa-4443-455a-9e4d-dffd46fb595d">

Currently testing with Debian-server: Results to come.

**Comment by DrEVILish** [comment]
When using an actual Loconet Server LbServer this isn't an issue.

Only an Issue when using JMRI / PanelPro - built-in LocoNet Server

**Comment by reinder** [comment]
Is it possible for you to run the server with a debugger attached? Maybe that can give a clue why it crashes when connected to JMRI's LBserver.

**Comment by reinder** [comment]
Before I forget, can you enable communication debug  logging for the LocoNet interface, you can find it on the LocoNet tab of the LocoNet interface dialog.

**Comment by DrEVILish** [comment]
> Is it possible for you to run the server with a debugger attached? Maybe that can give a clue why it crashes when connected to JMRI's LBserver.

I'm not sure how to do this, within the context of this build environment. I've not used CMake as part of an Application only built and debugged CPP projects directly, without the "extra" steps.


> Before I forget, can you enable communication debug logging for the LocoNet interface, you can find it on the LocoNet tab of the LocoNet interface dialog.

I also enabled PCAP to file:
[loconet_1_20240620_000937.pcap.txt](https://github.com/user-attachments/files/15906566/loconet_1_20240620_000937.pcap.txt)

`‘√≤°ˇì`
This was everything in the PCAP file



To clarify it's still crashing when using LocoNet on RedHat++ as well as the JMRI LocoNet Simulator.
Following Actions as you can see via the console->
<img width="909" alt="Screenshot 2024-06-20 at 00 11 58" src="https://github.com/traintastic/traintastic/assets/6287003/432656e8-6d9d-4947-bd51-77eee0d75957">

**Comment by gfgit** [comment]
Hi, I've not looked into the code but I recall a similar issue with Z21.
When disabling communications, the Interface object deletes it's Kernel.
It may happen that Kernel just posted a callback to EventLoop or it's IO context, and this callback captures variables by reference, for example raw "this" pointer.
If this callback is put in the queue and executed after Kernel is deleted you get a segmentation fault.

I saw this pattern multiple times in the code, so the issue here might be similar.

**Comment by reinder** [comment]
This pattern is used in all interface + kernel setups, I'll look into it.

**Comment by DrEVILish** [comment]
I've narrowed down the case to crash the server.

It's just happening on the LbServer.

LocoNet -> TCP binary -> I can enable and disable communications without the server crash
LocoNet -> LbServer -> on Disconnect : server crashes.

I think there is an infinite loop being caused by LbServer.

As soon as I open an LbServer connection the thread is pegged at 100%, have to SIGKILL.

Traintastic is getting a reply
`m_version = line.substr(7);` returns `VERSION:  IoTT lbServer 1.0.2`

After that nothing is sent back out, I think the error has already happened before "disconnecting" and it's stuck in a loop without the ability to properly close out the connection so it hangs.

This should be corrected by fixing #143 

I believe both issues are caused by the same underlying issue.

**Comment by DrEVILish** [comment]
`LBServerIOHandler::read()`
recieves these messages
```
VERSION IoTT lbServer 1.0.2[\r\n]
RECEIVE BB 01 00 45
SENT OK BB 01 00 45
RECEIVE E7 0E 01 03 00 00 00 04 00 00 00 00 00 10
```
However 
`if(startsWith(line, "RECEIVE ")){}`
`else if(startsWith(line, "SENT OK ")){}`
`else if(startsWith(line, "VERSION ")){}`
all return false, checked by adding
```
else {
  std::cout << "FAILED TO MATCH\n";
}
```
Which logs out "FAILED TO MATCH" when starting LocoNet.

**Comment by DrEVILish** [comment]
#147 fixes this

**Comment by reinder** [comment]
Awesome, great work @DrEVILish!

> A line ends with either a CR (13=0x0D) or LF (10=0x0A).
> source: https://loconetovertcp.sourceforge.net/Protocol/LoconetOverTcp.html#syntax

I've implemented it according to the specification which states it is OR not both, but being a bit more relaxed won't hurt :)
