### ISSUE TITLE
UI Issue -> Adding new Decoder, address annoyance.

### ISSUE THREAD

**Issue by DrEVILish** [traintastic/traintastic#145]
**Describe the bug**
When adding a new Decoder, DCC with a (Long address), Trying to type a 4 digit number, jumps around, makes it very difficult to enter a number using the keyboard. i.e. 1999. 
I believe it's doing input validation after each keypress. Meaning after highlighting the existing number and hitting 1, instantly adds a 28 to the end to bring it up to "128" the "minimum" Long address.

**To Reproduce**
1. Go to "Decoders"
2. Click on PLUS to Create new Decoder
3. Select "Protocol - DCC (Long Address)
4. Type a number.

**Expected behavior**
Finish typing instance before validating my input.

**Traintastic client:**
 - OS: macOS-14
 - Version: 0.3.0-dev

**Connected hardware**
N/A

**Comment by reinder** [comment]
@DrEVILish I made some adjustments, now it should be better.

For eye-candy the message can be a bit improved, but for now this should work :)

**Comment by DrEVILish** [comment]
Interaction is great, error message should have a better error message per box (obviously doesn't break anything).
I like how it snaps back to a correct value on "de-focus".

Happy to close this, but add the "info messages" to the "Nice to have" toDo pile.

**Comment by reinder** [comment]
There is a nice-to-have todo pile, but it is in my head :P, best would be to create a issue, I can add a nice-to-have label for that.

Closing this one :)
