### ISSUE TITLE
Connection Initializing - Sticky locks up UI - Multiple Interfaces

### ISSUE THREAD

**Issue by DrEVILish** [traintastic/traintastic#150]
**Setup**
Server & Client
Add "LocoNet" as Interface, Set a non-Loopback IP address and Port
Click "Toggle Connection"
In the Status Column of the Interfaces window "Initializing".
(You realise you haven't turned on your LocoNet Hardware etc. or got the IP/Port wrong)
Click "Toggle Connection"
Now in the "Disconnected State".

At this point Client UI is now frozen, between 16-33seconds (duration seems random).

**Expected**
On "Disconnect" any connection "Initialization" should be cancelled and reverted/reset.

**Logs**
I spammed the "Toggle Connection" button, while the UI was frozen. You can see the duration between "Comms: disabled" and the many "Comms: enabled" messages coming back.
```
2024-06-21 23:03:37.555212 world N1013: Communication: disabled
2024-06-21 23:03:53.284712 world N1012: Communication: enabled
2024-06-21 23:03:53.285347 world N1012: Communication: enabled
2024-06-21 23:03:53.285594 world N1012: Communication: enabled
2024-06-21 23:03:53.285706 world N1012: Communication: enabled
2024-06-21 23:03:53.285770 world N1012: Communication: enabled
```
```
2024-06-21 23:05:37.303536 server N1007: Listening at 0.0.0.0:5740
2024-06-21 23:05:40.757617 connection[192.168.20.57:61724] I1003: New connection
2024-06-21 23:05:48.488770 world N1012: Communication: enabled
2024-06-21 23:05:48.955824 world N1013: Communication: disabled
2024-06-21 23:06:21.781516 world N1012: Communication: enabled
2024-06-21 23:06:21.782942 world N1012: Communication: enabled
2024-06-21 23:06:21.783031 world N1012: Communication: enabled
2024-06-21 23:06:21.783070 world N1012: Communication: enabled
```

**Reproducable**
On any Server/Client without LocoNet hardware.

**Interfaces affected**
- [x] LocoNet :- LbServer
- [x] LocoNet :- TCP_Binary
- [x] DCC-EX :- Network (TCP)
- [x] ECoS
- [x] Märklin CAN :- Network (TCP)
- [x] XpressNet :- Network

**LocoNet Z21 and Märklin CAN UDP don't cause this issue**
I believe there's a missing "Disconnect" to send a Close or Cancel signal to the TCP connections.

**Comment by reinder** [comment]
A TCP connect usually has a connect timeout of ~30sec, that is what is causing the lock up, I need to make that async.
For UDP there is no issue, because UDP is not connection orientated, the messages are just sent.

**Comment by reinder** [comment]
@DrEVILish I've implemented async TCP connect for LocoNet, this should fix the "hanging". If you confirm I'll apply similar changes to the others.

**Comment by DrEVILish** [comment]
LocoNet Lb and TCP seems to be working as expected now for an "erroring" connection.

**Comment by reinder** [comment]
Thx for testing, I'm going to patch the others too (might take a few days due to leak of spare time :P)

**Comment by DrEVILish** [comment]
Probably won't have time to test and verify till early next week.

**Comment by reinder** [comment]
No problem 😁, we're all doing this in our limited spare time.

**Comment by reinder** [comment]
@DrEVILish I've patched the others too, just a notification, take your time :)

**Comment by DrEVILish** [comment]
Guess who's back :D

Here we go:
I don't have these devices on my network so expect it to fail gracefully. 
Tested with Both
- IP exists but connection refused
- IP Doesn't exist connection timeout.

ECoS causes a SEG FAULT
2024-07-08 13:46:50.587530 ecos_1 E2005: Socket connect failed (Connection refused)
zsh: segmentation fault  ./traintastic-server



DCC-EX Network
Märklin CAN :- Network (TCP)
XpressNet :- Network
**_Works as expected TICK_**




p.s. There is also a weird UI bug
Where I add a new Interface and the UI Interfaces table doesn't update. If I change the name or ID, it then populates the table. When it's like this I can't add or edit or delete the item as I'm guessing it's "ID" is missing. I have to make sure I "edit" the ID before closing that Interface window.
Let me know if you want more debug on this:
<img width="804" alt="Screenshot 2024-07-08 at 13 50 20" src="https://github.com/traintastic/traintastic/assets/6287003/a475bcf2-18f5-445b-8803-6b6757a0b15e">

**Comment by reinder** [comment]
Great to have you back here @DrEVILish

I'll look into the ECoS SEG FAULT, thanks for testing!

That is indeed a strange issue, if you close the *Interfaces* dialog and open it again, is the row still empty then. I'd expect it to be some kind of timing issue. Does it happen every time?

**Comment by reinder** [comment]
Now it should work for ECoS too :)

**Comment by reinder** [comment]
Shall we move the UI bug to a seperate issue?, then we can close this one once you verified the ECoS :)

**Comment by DrEVILish** [comment]
Moved UI bug to sepeart Issue,

Closing this one as fixes have been implemented.
