### ISSUE TITLE
UI Bug - Multiple Select

### ISSUE THREAD

**Issue by DrEVILish** [traintastic/traintastic#154]
**Describe the bug**
There is the ability to select multiple "Objects" (CMD + CLICK) but then the OK button is greyed out.

**To Reproduce**

1. Create a Train
2. Go to the Vehicles Tab
3. Add Vehicle
4. Select Multiple
5. OK Greyed out

**Expected behaviour**
I expect to add multiple items at the same time to a train.

**Version LATEST dev**

**Comment by reinder** [comment]
Yeah that is indeed a bit stupid, it is a generic object select dialog, but in this case it should support selecting multiple. Going to look into that, thanks for reporting!

**Comment by reinder** [comment]
@DrEVILish it is fixed :)

**Comment by DrEVILish** [comment]
Seems to work :D
