### ISSUE TITLE
Settings item needs a "Pretty Name"

### ISSUE THREAD

**Issue by DrEVILish** [traintastic/traintastic#155]
**Description**
Named Element in Client needs "Pretty Name"

<img width="394" alt="Screenshot 2024-07-08 at 13 38 36" src="https://github.com/traintastic/traintastic/assets/6287003/6265fefe-b349-43f8-bb52-31a42b0bf934">

Latest Client
Latest Server

**Comment by reinder** [comment]
@DrEVILish  thanks for reporting it, added the missing term.
