### ISSUE TITLE
Start Client and Server on Linux using deb packages

### ISSUE THREAD

**Issue by HeyJoFlyer** [traintastic/traintastic#158]
I have tried installing Trainsim on Windows, which worked very well. But when I installed it on Linux (Mint 21.1 Cinnamon) using the precompiled packages for Ubuntu 22.02 I wasn't able to start neither traintastic-server nor traintastic-client from the terminal neither did I find them in the start menu.

After a lot of searching I found the binaries here:

```
/opt/traintastic/bin/traintastic-client
``` 
and
```
/opt/traintastic/bin/traintastic-server
``` 

It would be very nice if the binaries were automatically added to $PATH or the path of the binaries was mentioned in the [manual](https://traintastic.org/en-us/manual/master#start-client), maybe like this:

When installing the precompiled packages the binaries are located in the /opt/traintastic/bin folder. To start the server and client execute `/opt/traintastic/bin/traintastic-server` and `/opt/traintastic/bin/traintastic-client` in the terminal respectively.

I have not done any further research whether this occurs on Raspberry Pi or Ubuntu 22.02 as well.

**Comment by reinder** [comment]
Thanks for reaching out.

Traintastic-server is installed as `systemd` service, but is disabled by default.

Traintastic client is doesn't have a menu entry yet, I didn't take the time to fix that.

Yeah, the manual is missing Linux explanation, I'll update that this weekend :)

Thanks for the feedback.

**Comment by reinder** [comment]
@HeyJoFlyer

I've updated the manual with instructions for Linux, see:
- https://traintastic.org/en-us/manual/master#start-server
- https://traintastic.org/en-us/manual/master#start-client

You can grab the latest development build at: https://traintastic.org/en-us/download/develop/master

**Comment by HeyJoFlyer** [comment]
Thank you!
And thank you so much for commiting to this project!
