### ISSUE TITLE
Crash in SubWindow destructor

### ISSUE THREAD

**Issue by gfgit** [traintastic/traintastic#16]
**Describe the bug**
Crash in exit with multiple sub Windows open

**To Reproduce**
0. Enable simulation, disable world edit
1. Go to 'Hardware -> Interfaces'
2. Click on 'Traintastic DIY'
3. Open Input Monitor
4. Go to 'Hardware -> Interfaces'
5. Open 'Boards'
6. Open 'board_1'
7. Play with objects in board and inputs
8. Close main window
9. Crash

**Expected behavior**
No crash.

**World export**
[4570a7db-9aeb-4c45-9cdd-847bb260f9cd.zip](https://github.com/traintastic/traintastic/files/10473291/4570a7db-9aeb-4c45-9cdd-847bb260f9cd.zip)

**Traintastic server:**
 - OS: [Ubuntu 22.04]
 - Version: [dev]
 - Compiler: GCC 12.2.0

**Traintastic client:**
 - Same

**Connected hardware**
None

**Additional context**
Crashes happens in `qmap.h` from [mainwindow.cpp L750](https://github.com/traintastic/traintastic/blob/6ad267f333a34b40a33c643f30bdc23bede2e21c/client/src/mainwindow.cpp#L750).
By this time `MainWindow` is already being destroyed and it's member `m_subWindows` is no longer available.
I suspect [mainwindow.cpp L540](https://github.com/traintastic/traintastic/blob/6ad267f333a34b40a33c643f30bdc23bede2e21c/client/src/mainwindow.cpp#L540) is not disconnecting it properly.

I cannot always trigger the crash. On Windows it never happens...
A possible workaround would be to explicitly delete all sub windows in MainWindow destructor instead of wainting QObject children deleter

**Comment by reinder** [comment]
Seems to be cause by the Input monitor, it is not in `m_subWindows` so it isn't disconnected properly....looking into it
