### ISSUE TITLE
Add Italian translation

### ISSUE THREAD

**Issue by reinder** [traintastic/traintastic#20]

**Comment by gfgit** [comment]
It Will be ready at beginning of february :)

**Comment by gfgit** [comment]
What is te meaning of LOB?

**Comment by reinder** [comment]
LOB = Length over buffers

Used by many manufacturers to describe the real world length of the model.

I checked the Roco website, the use *Lunghezza compresi respingenti* as *Length over buffers*. I used the abbreviation to keep the dialog a bit smaller.

**Comment by gfgit** [comment]
Ok. It will be incomprensible when abbreviated in Italian.
But maybe we can add a tooltip with longer description.

**Comment by reinder** [comment]
- Or just use the full text for clearity, 
- or we could just use length, although it is real world length of the model, while weight is real world weight, so that may be confusing.

Think we should just go with the full text option, do you agree? (The edit dialog needs a redesign too, I just built something that works for now)

**Comment by gfgit** [comment]
Maybe the label can be wrapped in multiple lines to keep width small

**Comment by reinder** [comment]
I'll change the English and Dutch text also to the *long version*.

**Comment by gfgit** [comment]
Hi, I'm looking for a way to remove old translations strings and add new ones.
I cannot get the scripts to work correctly, how should I use them?

Also while translating I noticed many strings are duplicated because they appear in different parts of the UI.
For consistency purposes I think they should be merged in some way to avoid different translations for the same phrase in multiple places.
Being a custom translation format I don't think any conventional tool might help here.
In my application I use Qt translation system which is quite easy to use, and Qt Linguist is really good at spotting similar phrases and possible mistakes.
But I understand you want to keep the server side independent from Qt.
Maybe gettext?

**Comment by reinder** [comment]
You can add missing by running (in project root):
`python3 utils/localeaddmissing.py shared/translations/en-us.txt shared/translations/nl-nl.txt`
first file is source (usually English), second is target to update.

`localeremoveold.py` works the same but removes string in destination that are not in the source.

Yes the are some duplicates, this can be reduced by setting the `DisplayName` attribute, else it will auto generate an identifier.

And yes I don't want Qt's system because I don't want the server to be dependent on Qt. The server currently only uses `en-us.txt` for writing the log file. (Log file is always English)
Windows tray menu is still hardcoded English.

Another translation system is an option, I build this to have something to start with. Most text identifiers are auto generated, this might not work well with some translations systems.

It's worth investigation the alternative options :) (in a separate issue :))

**Comment by reinder** [comment]
Another idea, build a python script to convert en-us.txt and it-it.py to it-it.ts then translate with QtLinquist and than convert it back to it-it.txt

**Comment by gfgit** [comment]
It can be done yes but I think then it's easier to change translation System.
About removing old translations I always need a "source" Like English which is considered update?
The script doesn't check the actually used string in source code files right?

**Comment by gfgit** [comment]
> You can add missing by running (in project root):
> `python3 utils/localeaddmissing.py shared/translations/en-us.txt shared/translations/nl-nl.txt`
> first file is source (usually English), second is target to update.

I run this command with italian translation and gives no output.
But then the file contains "#Garbage" string.
I think I accidentally modified some string ID but I don't know which row

**Comment by reinder** [comment]
Maybe it is a platform (line ending) issue, did you run it on windows?

**Comment by gfgit** [comment]
Yes on Windows 10

Il gio 26 gen 2023, 23:16 Reinder Feenstra ***@***.***> ha
scritto:

**Comment by reinder** [comment]
> It can be done yes but I think then it's easier to change translation System. 

I'm open for a better system that can work on both sides (server & client)

> About removing old translations I always need a "source" Like English which is considered update?

Correct

> The script doesn't check the actually used string in source code files right?

Correct, actually the traintastic-client is dumb, almost all dialog are auto generated at runtime based on the object that are sent by the server.

> I think the "log missing translation" is good but works only if that portion of code is run. Opening the client is not enough, you have to trigger the specifica dialog/message with missing translation to notice it

Correct, it is a bit a hack to get at least something.

Thought about that today. Part of the string id's could be generated by the server using some additional code. It could create for example an instance of each class and the get all the property/method/event names. For enum/set types auto generation is also an option. String id's in the client can be extracted with an bit of regex. Might not cover the full 100%, but most of it.

**Comment by reinder** [comment]
> Yes on Windows 10 

Found it, it is a line ending issue, if the text files have windows CRLF line endings it adds a garbage section. Going to correct that.
