### ISSUE TITLE
Simplify turnout/signal output mapping

### ISSUE THREAD

**Issue by reinder** [traintastic/traintastic#21]
Currently output mapping is a lot of work, the user needs to:
- Create outputs on the interface
- Then assign these to the turnout/signal
- Configure them

For most common situations it is much easier to just assign the interface and turnout/signal address, the software should create the output mapping automatically. The *advanced mode* should still be possible in case that is needed.

**Comment by reinder** [comment]
TODO: Support DDCext too, e.g. the [YaMoRC YD8116](http://yamorc.de/products/?singleproduct=1247) supports that.

**Comment by gfgit** [comment]
Should we support external turnout switching? Like if I switch a turnout from command station should the corresponding `Output` and `TurnoutRailTile` update their state?
Currently it doesn't seem to work

**Comment by reinder** [comment]
Yes, that is something that must be added.

This also raises some issues, if a turnout is locked (e.g. in the future by a reserved train path). How should that be handled?
- Send a command to set the turnout state back
- Estop the train and remove the reserved path
- ...

**Comment by gfgit** [comment]
Also turnout set to "pulse" output.
How do you detect incoming pulse?

**Comment by reinder** [comment]
A transition from low "0" to high "1", the strart of a pulse should be fine I think. It isn't a complete pulse, but that will problably work with most systems. Some systems also handle the pulse in hardware, when you set a output high the command stations sets it low after ~250ms or so. It is a bit gray area, that will require some testing to find "best practice" and what the user expects.
