### ISSUE TITLE
Restrict ID property values

### ISSUE THREAD

**Issue by gfgit** [traintastic/traintastic#22]
**Describe the bug**
When pasting 😀 (An Unicode emoji) inside Object's ID field weird things happen.

**To Reproduce**
1. Add a Train
2. Open it's properties
3. Run a second client and open train properties
4. Paste Unicode character inside ID field
5. Train List widget is correctly update on both clients
6. Clicking on train row inside the list to open properties results in an error message.

**Expected behavior**
Either work normally or prevent non-ASCII characters inside ID field.

**Traintastic server:**
 - OS: Windows 10
 - Version: [master]

**Traintastic client:**
 - Same

**Connected hardware**
None

**Additional context**
Server is getting '??' instead of the unicode char in [session.cpp](https://github.com/traintastic/traintastic/blob/f2f7f8b9338f14a048b2407d36cc0aaaebb0777d/server/src/network/session.cpp#L64)

**Comment by gfgit** [comment]
I think this exposes a bug because server/client don't handle Unicode correctly.
But It doesn't have to. Maybe documenting the supported character set is a good alternative.
To prevent inserting invalid characters [QValidator](https://doc.qt.io/qt-6/qvalidator.html) can be re-implemented and set on all `QLineEdit` maybe based on a new property flag

**Comment by reinder** [comment]
Nice discovery, I really like you testing :)

An object id may only contain 0-9 a-z and _ , the server should refuse the value otherwise (or change the value on world load), a client side filter would also be nice to inform the user about the limitation.

Did you try with the name property too?

Traintastic currently uses `std::string` everywhere containing utf8 encoded text. As long as the text isn't altered from within the server this works (but it isn't a good implementation)

**Comment by reinder** [comment]
Just did a quick check, there is no *id* validation... https://github.com/traintastic/traintastic/blob/master/server/src/core/idobject.cpp#L34

**Comment by gfgit** [comment]
Ok but I Wonder why initially the emoji is accepted in the ID and all client get update correctly.
Then after the change cannot open the object anymore because it's getting wrong ID with '??' instead of emoji.
The first message seems to have corre t unicode char but the next does not...

**Comment by gfgit** [comment]
I will experiment with QValidator

**Comment by gfgit** [comment]
Maybe related to this but I think there is a problem in changing ID in general while there are open windows referencing the object in question.
Mainwindow also builds a string representing a sub object Window which takes originale ID and is never updated

**Comment by reinder** [comment]
This thread has some interesting info. 

https://stackoverflow.com/questions/50403342/how-do-i-properly-use-stdstring-on-utf-8-in-c

Using std::string and std::u8string would be nice, std::string can than be used for properties that are ASCII only like *id*.

Requires C++20, we're currently on C++17. (Need to check if all current platforms support C++20)

**Comment by reinder** [comment]
Sorry missed that yesterday, had this issue open the whole time, didn't see your comment popup, now I refresh I see them.

> Maybe related to this but I think there is a problem in changing ID in general while there are open windows referencing the object in question. Mainwindow also builds a string representing a sub object Window which takes originale ID and is never updated

Yes indeed, that is an issue too. That must be fixed too.

`QValidator` would also be nice on the client side, best is that we can config it from the server by adding attribute to the property, then it can also be used for other properties that have a limited input set.

**Comment by gfgit** [comment]
> `QValidator` would also be nice on the client side, best is that we can config it from the server by adding attribute to the property, then it can also be used for other properties that have a limited input set.

I was thinking exactly that!

**Comment by reinder** [comment]
I just started to implement a server side check in in property `OnSet` and will add one when loading a world to make sure it only loads valid id's.

If you need some additional information about the property/attribute system, please let me know :)

**Comment by reinder** [comment]
*Id* property now only accepts a-z 0-9 _ and must start with a-z. (all lowercase)

If a world is loaded with an invalid *id* it logs:
```
2023-01-25 23:27:20.588332 traintastic C1001: Loading world failed (invalid object id value)
```

It gives no clue which one is invalid yet, but it shouldn't be possible unless someone edits the file manually.

**Comment by gfgit** [comment]
I began testing on client side.
`ObjectProperty` which stores the ID string seems to be constant (only set by constructor).
I hacked on `PropertyObjectEdit` to Request object and then connect to it's ID property chanded signal.
It's a bit complicated but I don't think server should emit XYZ changed for everey object referencing the modified object.

Also consider creating a new small helper class to manager `requestId` which would automatically cancel on destruction/re assignment and can be reset on completion.

**Comment by reinder** [comment]
The fact that the id can change makes it a bit hard.

Another possibility is to use a additional id (e.g. uuid) which is assigned when the object is created and never changes.

There are also object requests by *path*. E.g. `objectId.propertyName` so that will change then too.

**Comment by gfgit** [comment]
> Another possibility is to use a additional id (e.g. uuid) which is assigned when the object is created and never changes.

Personally I'm against UUID. I find it too much complex for this task. In the server sub object properties store a shared pointer so on Save the correct ID will be picked. The only problem is the client so the structure itself is fine. Serve sub object property could listen for ID change and send to client. Or server could register client in response to `GetObject` Requests so object which are not currently visibile don't unecessarely emit property changes

**Comment by reinder** [comment]
My idea was to only use the UUID on runtime, not for storage. But I agree, without an UUID is preferred.

Did some digging, wrote most of it 2y ago. For object properties the *object id* is sent as property value. So if the id of the object changes it just needs to send a property change event. That should be enough for the server to update the client.

The client then needs a fix for updating the sub window list.

**Comment by reinder** [comment]
Added a new message to request the object of a `ObjectProperty` without knowing the `id`, to eliminate the need for updating it.

It is now only used in `PropertyObjectEdit` as *name* for the object, this however is something that was on my list that needs to change. For the user it makes more sense to display the object name instead of the id.

**Comment by gfgit** [comment]
Hi, will test it next week.
Are nane unique in a world like IDs?
If not wuold it be good to show ID as tooltip for disambiguation?
Just a Quick idea about it, maybe is not really relevant

**Comment by reinder** [comment]
Thanks for testing, I'll continue with the other *id* related issues.

*Name* is just a user defined value unlike *Id* which must be unique within a *world* and may only contain `a-z0-9_`.

So a user can give two objects the same name, so duplicates can occur. So maybe we can do, e.g. `$name (#$id)`

**Comment by gfgit** [comment]
Not strictly related to this but I find `ObjectProperty` is a bit ambiguous.
It seems a generic object's property but instead means a property which value is another object.
This I think is especially confusing in latest commit where you request a sub object from parent object property

**Comment by gfgit** [comment]
I start to like this generic all kinds issue :)
Sorry for that...

Where does `errorStr` in [message.cpp](https://github.com/traintastic/traintastic/blob/536013c0cecf5c9a537983a2bfa92e4b761f8092/shared/src/traintastic/network/message.cpp#L39) come from?

**Comment by reinder** [comment]
> Not strictly related to this but I find `ObjectProperty` is a bit ambiguous. It seems a generic object's property but instead means a property which value is another object. This I think is especially confusing in latest commit where you request a sub object from parent object property [here](https://github.com/traintastic/traintastic/commit/86c4685b69dae805b20b0df0092a0890ce7e550c#r98734340)

`ObjectProperty` is a bit ambiguous indeed, for me as designer it totally makes sense because there is a generic `Property` too.

> I start to like this generic all kinds issue :) Sorry for that...

No problem, maybe I should enable the project discussion section, never used it, so we could try to discuss all kind of generic things :)
 
> Where does `errorStr` in [message.cpp](https://github.com/traintastic/traintastic/blob/536013c0cecf5c9a537983a2bfa92e4b761f8092/shared/src/traintastic/network/message.cpp#L39) come from?

Nowhere, that file is unused, everything is in the header, I accidentally commited it in the first commit, see https://github.com/traintastic/traintastic/commit/3fd0aa18be5e8dc1342f60061f932879cea7b485
I'll remove it.

**Comment by reinder** [comment]
@gfgit added a fix to keep `m_subWindows` up2date. The only thing now left now is the *id* value in an oblect property edit. But that is something that can be fixed later. Could you test if it now works as expected?
