### ISSUE TITLE
Cannot open z21 properties

### ISSUE THREAD

**Issue by gfgit** [traintastic/traintastic#29]
**Describe the bug**
Hi, I've just built client with master branch on Windows 10 and added Z21 interface along traintastic DIY
None of them is connected.
I can open Traintastic DIY properties but not z21 ones.
Debugging is quite painful because GDB does not like lambdas and for some reason the cursor in source code is offset by one line below the actual instruction.
I've set a breakpoint [here](https://github.com/traintastic/traintastic/blob/b6379bf5f89eb54b19b5c6c7cd8817fe757f5804/client/src/widget/objectlist/objectlistwidget.cpp#L181) but `showObject()` is never called which is weird.
Also `getSelectedObjectIds()` is offset while stepping into it.

As a bonus launching debugger takes ages because it loads thousands of DLLs while doing so on linux just takes a few seconds and property window opens just fine.

**Comment by gfgit** [comment]
There is also a bug in `ObjectListWidget` maybe related to this.
If you add multiple objects and delete the first one, the last row disappeart leading to think it deleted last object but it actually deleted first one.
When adding a new object sometimes it shows ghost object which was recently deleted.
Closing and reopening sub window refreshes the table so it's like a client side cache issue.
Connecting 2 clients shows erroneous table items in both.
I'm really stuck with debugging. GDB jumps randomly to other functions on Windows and seems to skip calls so I don't know what to do.

**Comment by reinder** [comment]
Thanks for the report, I'll look into it.

The list not updating properly is a caching issue. I discovered it some time ago but forgot.

On windows I use VS2017 community edition. I'll see if it has the same issue as when using MinGW.

**Comment by gfgit** [comment]
I found some useful GDB commands to speed up loading.
- Tell GDB to avoid loading every DLL existing on Earth (traintastic seem to need all of them...)
`set auto-solib-add off` 
- Then load Qt libraries which are useful to look at internal errors with:
`sharedlibrary Qt5*`
I still need to figure out the regular expression syntax but this seems good enough for now.

Theese command must be run before starting the inferior otherwise it's too late to stop GDB loading every DLL but still can be useful.
As they are really useful to make debugging more responsive I think we should add them somewhere like inside `README.md` file. What do you think?

**Comment by gfgit** [comment]
About the cache issue I've made a workaround. Each time an object is deleted, call 'updateRegion()` with every row below removed one in `ObjectList`.
But that's implies re-sending all data to connected clients.
A better way would be sending a new message with the row to remove but client's `TableModel `stores `ColumRow` as a map key.
This means all row greater than removed one must update the key so must be removed and inserted again in the map which is not ideal either.

Also `ObjectList` uses `ObjectListTableModel` members but the type is only forward declared.
The header cannot be included because there is a circular dependency.
It's difficult to debug because GDB refuses to set breakpoints in headers, I suspect because functions get inlined

**Comment by reinder** [comment]
> About the cache issue I've made a workaround. Each time an object is deleted, call updateRegion() with every row below removed one in ObjectList.
But that's implies re-sending all data to connected clients.

It works at least, for now good enough, it isn't the best solution but the current implementation has some limitations. I'd like to add sort support on the client, with the current implementation this has to be done on the server side as the client may not have all data present. To reduce the load on the server it would be better to do it on the client. But then the client needs al the data.

> A better way would be sending a new message with the row to remove but client's TableModel stores ColumRow as a map key.
This means all row greater than removed one must update the key so must be removed and inserted again in the map which is not ideal either.

True, the remove and re-insert can be done more efficient using C++17 extract/insert, see: https://github.com/traintastic/traintastic/blob/ea3fbd80227ebfc48a6cc5edba05094fefdecebd/server/src/core/idobject.cpp#L42
The node is then reused saving a memory allocation and deallocation :)

> Also ObjectList uses ObjectListTableModel members but the type is only forward declared.
The header cannot be included because there is a circular dependency.
It's difficult to debug because GDB refuses to set breakpoints in headers, I suspect because functions get inlined.

That's another reason why the list object needs a refactor. (MSVC refuses to compile it, that's why I use clang on windows)

For now a quick is fine, after the 0.2 release it can be refactored :)

**Comment by reinder** [comment]
So you are trying:
- Create a new world
- Open interface list
- Create Traintastic DIY -> dialog opens
- Create Z21 -> no dialog opens

Is that correct?

Just tested this on:
- Ubuntu 20.04 / gcc 9.3.0
- Windows 10 / server: clang 12 / client: vs2019
For both interfaces the dialogs appear.

**Comment by gfgit** [comment]
Actually it works for me too if I create a new world.
Then something must be wrong with the old world which I exported and attached below.
Importing it back crashes the server...
[Test Simulation 2023-02-06.zip](https://github.com/traintastic/traintastic/files/10669713/Test.Simulation.2023-02-06.zip)

**Comment by gfgit** [comment]
Of course when I try debugging server it doesn't crash anymore :)))))

**Comment by reinder** [comment]
I imported *Test Simulation 2023-02-06* on Linux and Windows, no issue, it just works as expected :)

**Comment by gfgit** [comment]
Now I can import too and still has the bug

**Comment by reinder** [comment]
Does the bug occur if you use the latest master build from https://traintastic.org/en-us/download/develop/master ?

**Comment by reinder** [comment]
I'll try again tomorrow with address sanitizer and undefined behavior sanitizer enabled.

**Comment by gfgit** [comment]
- I've cleared directories in AppData and installed `Build #543`.
- Run server.
- Run client -> Hangs in Connect dialog, all greyed out indefinitely
- Closed and reopened Client, now connects fine with some delay
- Interfaces are swapped (z21 is first)
- Can open correctly Traintastic DIY
- Cannot open z21 but a small window appears in a random position then it's hidden immediately after.
(This happens also with my local build)

**Comment by gfgit** [comment]
I've managed to crash server again when importing but it happens randomly

**Comment by reinder** [comment]
>     * Run client -> Hangs in Connect dialog, all greyed out indefinitely (seems to happen reliably)

Yes, I'm aware of this issue, can't figure yet what is causing it. I'll create an issue for it.

>     * Closed and reopened Client, now connects fine with some delay

Cancel the connect and then connect again also works :)

>     * Interfaces are swapped (z21 is first)

The item order isn't stored, so it depends on the order they are created in when loading. (Implementing ObjectList sorting #32 will resolve this, the client should remember the last sort option)
 
>     * Can open correctly Traintastic DIY
> 
>     * Cannot open z21 but a small window appears in a random position then it's hidden immediately after.
>       (This happens also with my local build)

I saw some small windows to, only happens on windows when not setting the parent on widget creation. See e147560e4c355c75fb686a7b5d52dc9f3ee68c73

Maybe one of the widget constructors fails somehow stopping the creation process. It happens with you MinGW build and also with the GitHub action built version. On my Win10 VM it isn't an issue...these must be a difference somewhere.

> I've managed to crash server again when importing but it happens randomly

Any idea where the crash happens? (can you get a callstack?)

**Comment by gfgit** [comment]
> Maybe one of the widget constructors fails somehow stopping the creation process. It happens with you MinGW build and also with the GitHub action built version. On my Win10 VM it isn't an issue...these must be a difference somewhere.

From my understanding Qt widgets internal state (like native Windows) are created on first show but I may wrong and still this may not be relevant.
Is GitHub Action also using MinGW? I don't yet understand how they work...

About the server crash, it happened twice with the downloaded version which I'm unable to debug with Gdb. All I can get you is the exception offset registered by Windows event System if it's useful.
Let me know.

**Comment by reinder** [comment]
The downloads on the website are all *release* versions without debug info.

The GitHub action built version for Windows is built using VS2019, the client uses the MSVC compiler, the server uses clang. Some time ago I tried to setup is for MinGW to, but didn't get it to work properly.

For now I'm removing the *0.2 "Berlin"* milestone, don't want to delay it longer. One this it fixed we can do a patch release.

**Comment by reinder** [comment]
@gfgit are you still experiencing this issue now you're working on some Z21 improvements?

**Comment by gfgit** [comment]
I've tested it now and seems to work.
