### ISSUE TITLE
PropertyTextEdit: on every letter the cursor is reset to start

### ISSUE THREAD

**Issue by gfgit** [traintastic/traintastic#4]
**Describe the bug**
Every key press or input event in [PropertyTextEdit](https://github.com/traintastic/traintastic/blob/master/client/src/widget/propertytextedit.cpp)

**To Reproduce**
1. Add a train (Objects -> Trains -> +)
2. Go to the 'Notes' tab of train properties window
3. Type something, it will get inverted

**Expected behavior**
Text is entered normally

**Traintastic server:**
 - OS: [Windows 10]
 - Version: [master]
 - Compiler: MinGW 11.2.0

**Traintastic client:**
 - OS: [Windows 10]
 - Version: [master]

**Connected hardware**
Nothing

**Additional context**
The problem is the circular signal connection.
`PropertyTextEdit::textChanged()` is connected with a lambda to `m_property.setValueString(toPlainText());`
This goes to the the server and comes back emitting `Property::valueChangedString()` which is connected to `PropertyTextEdit::setPlainText()`

This signal connection does not seem to trigger an infinite loop because maybe server is checking string contents for change and is not emitting back `Property::valueChangedString()` the second time.
But unfortunately `PropertyTextEdit::setPlainText()` fully resets the document (a bit expensive for long texts) and resets cursor to start.

**NOTE**: as the text is always converted to plain text, it might be more appropriate to derive from [QPlainTextEdit](https://doc.qt.io/qt-5/qplaintextedit.html)
But this is not related to the problem described above...

**Possible Solution 1**
Add Ok/Cancel buttons and call `m_property.setValueString(toPlainText());` when pressing Ok.
*Pros:*
- avoid looping and avoids emitting signal on every key stroke which I don't think is a really useful thing.
- You get opportunity to cancel modifications

*Cons:*
- Value is not synced immediately with server, multiple clients might edit at same time -> needs locking
- Ok/Cancel does't look really good inside a QTabWidget

**Possible Solution 2**
Check string contents on `Property::valueChangedString()` (a bit expensive for longer texts)
Compare with current text, if no change then do nothing
*Pros:*
- You can keep typing normally
- Value is constantly synced with server

*Cons:*
- Expensive string compare, which I think is already done by server

**Possible Solution 3**
This one is just for fun...
Add ability to "ignore" property changes made by client itself, react only to changes made by other clients or server itself.

**Comment by reinder** [comment]
Thanks for your thorough analysis.

I had this issue in another widget too: [PropertyLuaCodeEdit](https://github.com/traintastic/traintastic/blob/master/client/src/widget/propertyluacodeedit.cpp#L40), resolved it using solution 2, not ideal. But solution 1 is even worse (no offense ;)) locking will probably introduce more issues. Solution 3 is interesting, but not possible with the current implementation. There is no information on who caused a property change, might get difficult too, a property change can trigger all kind of things.

For now solution 2 is best, usually these string aren't very large so the performance impact is low.
