### ISSUE TITLE
Server compilation speed

### ISSUE THREAD

**Issue by gfgit** [traintastic/traintastic#43]
**Describe the bug**
The file `world.hpp` is included in many places and includes many headers.
Many properties can be forward decleared like this:
```
class AnIncompleteType;
std::shared_ptr<AnIncompleteType> ptr_to_incomplete;

class World
{
  ...   
  ObjectProperty<AnIncompleteType> prop_with_incomplete_type;
};
```

This compiles with MinGW and should speed up quite a lot if done in all places

**Comment by reinder** [comment]
That would be really nice, reducing compilation time!

Can you modify a few as test and create an PR, then I start the CI/CD to verify if the other compilers agree. I had issues regarding forward declaration is the past, especially with MSVC.

**Comment by gfgit** [comment]
What do you think about splitting `objectproperty.hpp` and move function bodies to a new file say `objectproperty.ipp`
(NOTE: the extension are different)

This way MinGW should not stumble on `std::dynamic_pointer_cast<SomeIncompleteType>(...)`
Don't know about other compilers

**Comment by reinder** [comment]
Debug build on Dell XPS 13 (7390): `time make -j8 traintastic-server`

Old situation:
```
real    9m26,340s
user    66m19,987s
sys     2m51,884s
```

Split `objectproperty.hpp` and using forward declarations in `world.hpp`:
```
real    6m5,991s
user    44m4,236s
sys     1m47,011s
```

`ObjectProperty<>` is used in other files to, so that may reduce the build time a bit more :)

@gfgit Good suggestion 👍

**Comment by gfgit** [comment]
I've noticed last MinGW command which should link the server has a `-Wl,--out-implib=libtraintasticserver.dll.a`
This is a sort of import library for linking other DLL against server executable.
We do not currently need this functionality and I suspect it's slowing compilation time.
Need to investigate

**Comment by reinder** [comment]
I just did a few tests on my laptop running Ubuntu 22.04.

Using: gcc version 11.3.0 (Ubuntu 11.3.0-1ubuntu1~22.04)

Linking a Debug traintastic-server takes ~15sec using the standard linker, when using `-fuse-ld=gold` ~4sec.

200sec+ is very long and annoying....maybe it is MinGW related, can you try to use Clang? (not sure if MSVC works, had template related issue in the past)

p.s. A virus scanner can also cause a slow down, it might help to exclude the build folder to speed up the process.

**Comment by gfgit** [comment]
> Linking a Debug traintastic-server takes ~15sec using the standard linker, when using `-fuse-ld=gold` ~4sec, `-fuse-ld=lld` (LLVM linker) is even faster ~765ms!

I finally installed Clang 16!
Configuring CMake with Clang is not working because of missing `oldnames.lib`, I guess Visual Studio is needed...
But -fuse-ld=lld is working and it's insanely fast!!!!!!

**Comment by reinder** [comment]
So now you're using MinGW and Clang as linker?

**Comment by gfgit** [comment]
Hi Reinder! I'm having some troubles with 2FA so I may not respond for a few days. Are you closing this issue for missing info or is it solved?

**Comment by reinder** [comment]
Hi Flippo, long time no see :)

As linking speed is much faster now when using the clang linker I thought we could close it.
Full rebuilds are still time consuming, but I don't expect that's easy to resolve. I'd expect the slow compilation speed mainly caused by using boost.
