### ISSUE TITLE
Server crash on 

### ISSUE THREAD

**Issue by gfgit** [traintastic/traintastic#46]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**World export**
If applicable, please attach an export of the world that has the bug. (In traintastic-client: *File* -> *Export world*)

**Traintastic server:**
 - OS: [e.g. Windows 10, Ubuntu 20.04]
 - Version: [e.g. 0.1.1]

**Traintastic client:**
 - OS: [e.g. Windows 10, Ubuntu 20.04]
 - Version: [e.g. 0.1.1]

**Connected hardware**
e.g. ESU ECoS, Intellibox Basic, DR5000

**Additional context**

**Comment by reinder** [comment]
probably submitted by accident, see #47, closing it.
