### ISSUE TITLE
Server hang on communication disabling

### ISSUE THREAD

**Issue by gfgit** [traintastic/traintastic#53]
**Describe the bug**
Simple world with Z21 connected

**To Reproduce**
1. Open attached world
2. While disconnected from Z21, power on and run
3. Put Z21 in Emergency Stop state
4. Open Server Log view
5. Enable communication
6. You will see world going in stop and possibly a Broadcast flag mismatch warning
7. Disable communication
8. Server hangs for a socket error, something like "connection forcibly interrupted"?

**Expected behavior**
No hang

**World export**
[Test Local Z21 2023-04-13_new.zip](https://github.com/traintastic/traintastic/files/11224840/Test.Local.Z21.2023-04-13_new.zip)

**Traintastic server/client:**
 - OS: Windows 10
 - Version: last commit of PR #51
 - Compiler: MinGW

**Connected hardware**
Z21ServerEmulator running on localhost

**Additional context**
A socket exception is catched on mani() so no backtrace. And it is not happening always...

**Comment by gfgit** [comment]
Found the issue but I need suggestions.
Z21's `ClientKernel` internally calls: (NOTE: lambda capture `this` to access `this->m_logId`)
```
EventLoop::call(
        [this, msg=toString(message)]()
        {
          Log::log(m_logId, LogMessage::D2001_TX_X, msg);
        });
```

When communication are disabled, kernel shared pointer is reset -> `ClientKernel` object deleted.
But event loop sometimes still has to process the lambda above so `m_logId` is accessed after kernel is deleted.

A possible solution is to get a shared pointer inside the lambda to avoid it being deleted while lambda is executed.
This should be done for every lambda and also for other command stations which might present same race behaviour.

Drawback is that Kernel object might have connections inside it's parent hardware interface and the interface expect to have deleted the kernel immediately but in reality it might still use some callbacks or access some interface members

**Comment by gfgit** [comment]
In this particolar case we could just capture a copy of log ID and not capture `this` at all.
But in other lambdas a reference to `this` is needed and we should use a different method.
Also I'm not sure `shared_ptr` is thread safe

**Comment by gfgit** [comment]
This problem is partially fixed inside #59 but other lambdas passed to `EventLoop::call(...)` are capturing `this` so we need to change them also.
Other interfaces might have the same issue.

**Comment by reinder** [comment]
Think we should change the kernel cleanup a bit, instead of doing `m_kernel.reset();` direct we do delay is by posting the cleanup to the eventloop, as it processes everything in order, any pending log message is then processed before the kernel is destroyed.

**Comment by reinder** [comment]
> Think we should change the kernel cleanup a bit, instead of doing `m_kernel.reset();` direct we do delay is by posting the cleanup to the eventloop, as it processes everything in order, any pending log message is then processed before the kernel is destroyed.

Implemented in https://github.com/traintastic/traintastic/commit/161a0e9521bc3ef30c799234d3f82d84b971afdd, could you test if this resolves it?

**Comment by gfgit** [comment]
I cannot reproduce anymore!
