### ISSUE TITLE
Boost connection destructor

### ISSUE THREAD

**Issue by gfgit** [traintastic/traintastic#58]
Hi it seems `boost::signal2::connection` does not disconnect automatically in destructor.
Many objects have connections inside, e.g. `BlockInputMapItem` connects to `Input::onDestroyed` to clear property value.
Now with PR #54 also train vehicle items connect to vehicles. The problem is that trains get deleted before vehicles.
When eventually vehicles are deleted, signal is fired and connection is still in place but destination object was already deleted.
This causes an assert fire, but could have been also a segmentation fault in some random other place.

**Comment by gfgit** [comment]
Disconnecting `TrainVehicleListItem` in destructor from `RailVehicle` seems to fix the crash.
But also the other objects I think should do the same for clarity even if they don't cause crash.
Object destructor order might be changed or new connections made between objects so the problem could arise again later

**Comment by reinder** [comment]
I had that issue with `boost::signal2::connection` too and found out that it isn't disconnection on destroy :)

Not sure if I checked all signal connections back then. Good practice would be to always disconnect them. I'll check that.

**Comment by reinder** [comment]
I've searched for `.connect(` and checked for proper signal disconnects, there were a few issues. It should be resolved now.

**Comment by gfgit** [comment]
Is there a reason to disconnect inside `destroying()` rather than destructor?
I will update PR #54 for consistency

**Comment by reinder** [comment]
The purpose of `destroying()` is to clean up and drop all references so the `std::shared_ptr` refcount will become zero and the object is deleted. Disconnecting the signals in `destroying()` ensure that no signal callback's are made to the object when it is supposed to die.
