### ISSUE TITLE
Integrate with poeditor.com for translations

### ISSUE THREAD

**Issue by reinder** [traintastic/traintastic#63]
Using the poeditor.com service, translating the software is much easier for everyone.

ToDo:
- [x] Import strings @ poeditor.com
- [x] Change translation file format (multiline support?)
- [ ] [https://poeditor.com/help/how_to_translate_a_language_file_from_a_github_project](How to translate a language file from a GitHub project)

**Comment by reinder** [comment]
@gfgit we talked about a better translation system, this poeditor.com service looks very nice :) I've already requested Open Source project status (free plan is 1000 strings limit).

**Comment by reinder** [comment]
Using the [poeditor](https://github.com/lukin0110/poeditor-client) utility, the translations can now easily be synced.

**Comment by gfgit** [comment]
@reinder  we still need an automatic way of extracting strings from source code
This might prove difficult because sometimes translation keys are dynamically built at runtime

**Comment by reinder** [comment]
@gfgit for the static ones in the client a bit of Python could be used to extract all `Locale::tr("...")` usage. For the dynamic ones this won't work. That has to be done at runtime.
