### ISSUE TITLE
Infinite recursion in SignalPath

### ISSUE THREAD

**Issue by gfgit** [traintastic/traintastic#7]
**Describe the bug**
When making a rail loop with signal but no blocks inside a board, the discovery mechanism will go into infinite recursion and eventually crash because of limited stack space.

```
Board:
  ___
 /   \
|     o  <-- Signal
 \___/
```

This is the root cause: [signalpath.cpp](https://github.com/traintastic/traintastic/blob/722b9650fa3915bbe4ddce2a63d74efe5d11dfcb/server/src/board/map/signalpath.cpp#L280)

**To Reproduce**
1. Add a board
2. Build the rail loop, add a signal
3. Power On the world
4. Server disconnects because it crashes

**Expected behavior**
As the layout is stupid maybe a warning to the user might be a good thing.
Or just avoid crashing :-)

**Additional context**
The problem is very frustrating because you loose unsaved changes but also because if saved when powered off,
at next server launch it will load last world and try to power it and crashes.
This means having to manually delete world file but maybe there is another solution.

**Comment by reinder** [comment]
Yes indeed, it doesn't check for this. It should not crash when building something like this.
