### ISSUE TITLE
Crash when deleting Train

### ISSUE THREAD

**Issue by gfgit** [traintastic/traintastic#70]
**Describe the bug**

First apply PR #54 

1)
When deleting a `TrainVehicleListItem` from Train Vehicles tab nothing happens, if you try again it crashes.
This is because of line 75 `vehicle = nullptr` which will fail because we prevent null vehicles thus leaving the item "half destroyed" (`m_dying = true` flag)
Second time it gets deleted it fails on asserting `m_dying = true`
**FIXED:** by using `setValueInternal()`, in recent commit of #54 

2)
Deleting a Train sometimes calls `TrainVehicleListItem` destructors, sometimes it doesn't. When it does it fails in `assert(!vehicle)` because `TrainVehicleListItem::destroying()` is never called.
The code is very similar to `BlockInputMap` so same bug may be present

**Comment by reinder** [comment]
I had that kind of "keep alive" issues with other objects too. Added some tests to make sure it all works properly, we should do that for train and rail vehicles too.

> We should not allow deleting an active Train, show a warning and suggest to deactivate first.

I agree :) 

And what about a train that is assigned to a block, does deactivating remove it, or must is be removed form the block(s) first?

**Comment by gfgit** [comment]
> And what about a train that is assigned to a block, does deactivating remove it, or must is be removed form the block(s) first?

It would be correct and clean to first remove from Block but it also would be too long.
1. Try delete, fail
2. Try deactivate, fail
3. Find Block and unassign
4. Deactivate
5. Delete

Too many steps, a cool thing would be a dialog saying "would you like to deactivate and then delete? Every Block will be cleared too"
So one click does everithing

**Comment by reinder** [comment]
Yeah that would be best. That is something we should add on the client side.

Currently most of the UI is build automatically based on the objects, but for a good user experiance we need to build some custom dialogs and code to handle situations like this :)

**Comment by gfgit** [comment]
Problem with this is that the check is done at client side and some other client can delete Train while dialog is open

**Comment by reinder** [comment]
Yes, but that is something that always can happen, as long as the question is open some other client can delete it. We only must make sure that is doesn't have unwanted side effects. (Currently the *remove train from block* doesn't have a train parameter, that must change so it only removes the train it intents to remove.)

**Comment by reinder** [comment]
@gfgit improved the remove train from block action, see [10c7d73](https://github.com/traintastic/traintastic/commit/10c7d732d1c9064148840b5cd933e13871ec5299). Based on the error code we can improve the UI further by asking the user what to do next, for now just an error message.

**Comment by gfgit** [comment]
Hi. I think error messages now conflict with PR #115

**Comment by reinder** [comment]
You're right, I'll renumber them, you were first :P

**Comment by reinder** [comment]
@gfgit do you still have this issue or can we close it?

**Comment by gfgit** [comment]
Hi. I get a crash when closing World.
This is because `TrainVehicleListItem::destroying()` is not called by `ObjectVectorProperty<TrainVehicleListItem>` destructor.
My question is:

- Should I manually call `TrainVehicleListItem::destroying()` before `ObjectVectorProperty<TrainVehicleListItem>`  destructor?
- Or is it fine to not call it since all obkects get destroyed anyway and so I should not `assert(!vehicle)` inside `TrainVehicleListItem` destructor?

**Comment by reinder** [comment]
`TrainVehicleListItem` does not exist on the `master`, which development branch are you using? (The PR #54 one?)

We should write some test to cover those cases, that makes it easy to make sure it doesn't break in the future due to other changes, let me know if you need help :)

**Comment by gfgit** [comment]
Hi. Yes I'm talking about PR #54
It needs refactoring for the speed matching part but the `TrainVehicleListItem` seems already good.
My question is how to fix the deletion of Train as explained above.
Should I call `destroy()` manually or avoid asserting in destructor?
I still did not fully understand Traintastic `destroy()` mechanism.
Anyway this issue is not urgent as I need some time to think about speed matching part and do some tests.

**Comment by reinder** [comment]
Traintastic uses `std::shared_ptr` for memory management, but if two objects have a reference to each other they will never be deleted. For that there is `destroy()` when called, the object should drop all its references to other objects, that will in the end result in zero refs to the object so it is deleted.

**Comment by gfgit** [comment]
Yes it's fixed now. You can close it!
