### ISSUE TITLE
Extend DecoderController

### ISSUE THREAD

**Issue by reinder** [traintastic/traintastic#72]
Currently all protocols, addresses and speedsteps can be selected freely in a `Decoder`. For many interfaces there are certain limitations. By limiting the `Decoder` to what the command stations supports makes t easier for the user to configure it correctly and makes it possible to use this info in `RailVehicle` for a speed table and acceleration/deceleration, see #59.

Tasks:
- [x] Limit available protocols to the ones supported by the interface.
  - [x] DCC++
  - [x] ECoS
  - [x] LocoNet
  - [x] XpressNet
  - [x] Z21
- [x] Limit address range to the selected protocol.
  - [x] DCC++
  - [x] ECoS
  - [x] LocoNet
  - [x] XpressNet
  - [x] Z21
- [x] Limit speedsteps to what is supported by the interface.
  - [x] DCC++
  - [x] ECoS
  - [x] LocoNet
  - [x] XpressNet
  - [x] Z21
- [x] Remove `Auto` / `Custom` protocol ??
- [x] Add `None` protocol ??
- [x] Split DCC into seperate DCC short and DCC long, then remove longAddress flag

**Comment by gfgit** [comment]
Why is it checking values from interface in protocol OnSet callback and checking from protocol attribute values in checkprotocol()?
Also doesn't setting attribute values automatically prevent setting invalid value without additivo al OnSet check?

**Comment by reinder** [comment]
> Why is it checking values from interface in protocol OnSet callback and checking from protocol attribute values in checkprotocol()?
Because I wrote it in different evening I think :P no good reason.

> Also doesn't setting attribute values automatically prevent setting invalid value without additivo al OnSet check?

No not yet (it crossed my mind), but it should, at least for enum values, setting a non listed value is still possible by using `setValueInternal`, I'll change that.

**Comment by reinder** [comment]
Functionality is there, now all interface/protocol limits must be checked and set.

**Comment by reinder** [comment]
@gfgit I was just reading the documentation of the Z21 `LAN_GET_LOCOMODE` and `LAN_SET_LOCOMODE` commands. Based on the docs each locomotive address is either DCC or Motorola (MM).

Currently there is no limit for that. As long as both aren't in use at the same time it could work in theory, but I think it is best to block it. I suggest to add something like `changeInputChannelAddress` to make sure a protocol/address combination is only assign to one decoder, limiting a address to DCC or Motorola can also be enforced then.

**Comment by reinder** [comment]
@gfgit can you have a look? Any comments or suggestions? :)

**Comment by gfgit** [comment]
Hi, didn't test it yet but looks good!
One thing: since you didn't make a PR yet, edit the commit which edits both translation and loconet.
I would keep translations edits in a single separate commit

**Comment by gfgit** [comment]
When it will be merged I'll rebase my PR on top of this and maybe split fixes which can be merged and new additions which need testing

**Comment by reinder** [comment]
> Hi, didn't test it yet but I will soon! It looks good. One thing: since you didn't make a PR yet, edit the commit which edits both translation and loconet. I would keep translations edits in a single separate commit. I'm talking about [80aa475](https://github.com/traintastic/traintastic/commit/80aa475c4616b4c2b6fa5d984229ea4318777438)

Thanks, I usually add/remove the translation(s) in the same commit as the code changes as they are related. (mainly because I'm used to it :P) Whats your motivation to use separate commits? (I'm open to suggestions :))
