### ISSUE TITLE
No connection to my DR5000

### ISSUE THREAD

**Issue by mikemc9000** [traintastic/traintastic#83]
I was unable to establish a connection to the DR5000, neither in LocoNet TCP Binary mode nor in Z21 mode.
![digi03](https://github.com/traintastic/traintastic/assets/150791245/15233f85-090a-4b38-ba03-38bc3aecb9c5)

**Comment by reinder** [comment]
@mikemc9000 what does the server log say?

You can find the server log in the client by:
- Pressing the **F12** hotkey or
- via the mainmenu: *View* -> *Server log*

**Comment by mikemc9000** [comment]
There is nothing in the server logging about a connection to the DR5000. At what point should the connection take place? Should there be error messages? With other tools I can connect to the DR5000, so no network problem.
![digi04](https://github.com/traintastic/traintastic/assets/150791245/f2e74ae1-9c77-4d63-93a5-70e85f3224b6)

**Comment by reinder** [comment]
![dr5000-connect](https://github.com/traintastic/traintastic/assets/886282/0f6bb5bc-54f0-40d4-83ab-42f1556a6971)

After entering the connection details:
- Press the connect button (1), this will initiate the connection with the DR5000
- The status "dot" is gray when offline, purple when initializing, green if connected and initialized and red in case of an error.

**Comment by reinder** [comment]
@mikemc9000 did it work? (Then I'll close the issue)

**Comment by reinder** [comment]
No further response, I consider it resolved.
