### ISSUE TITLE
Windows crash

### ISSUE THREAD

**Issue by mikemc9000** [traintastic/traintastic#84]
From time to time my entire Windows freezes. It then no longer responds at all, only a hard reset can be carried out. This happens to me on average once an hour. I haven't been able to reproduce exactly when this happens, but only when I use traintastic. On different computers.

**Comment by reinder** [comment]
Does it happen with pre build development build and/or self build versions?

**Comment by reinder** [comment]
@mikemc9000 is this still relevant?

**Comment by reinder** [comment]
Closed, no response for 5 months, please reopen if it is still relevant.
