### ISSUE TITLE
DR5000 with Z21 no power on is possible

### ISSUE THREAD

**Issue by mikemc9000** [traintastic/traintastic#85]
power off is ok

**Comment by reinder** [comment]
Can you provide a bit more detail on this one? I don't fully understand it yet :)

Is Traintastic's power state not synced with the DR5000 when using Z21 communication?

**Comment by gfgit** [comment]
Don't know if it's relevant here but I think when connection is established each side tells the other which state is in it. So there might be a race condition.

**Comment by gfgit** [comment]
Hi @mikemc9000 I've noticed this issue and made some changes to the way power state is sent and received from Z21 or compatible devices.
See pull request #131 
Now it works on my DIY Z21 but could you confirm it's working on DR5000 too?
