### ISSUE TITLE
DR5000 with loconet: throttle a locomotive not possible

### ISSUE THREAD

**Issue by mikemc9000** [traintastic/traintastic#86]
With loconet I can only display the locomotive speed, but not control it. The display changes, but the locomotive does not move. If I control the locomotive with another program, the speed display is updated, but no control is possible. Light On/Off works!

**Comment by reinder** [comment]
Is Traintastic in *RUN* state? If Traintastic is in *STOP* state, you can set the speed but it isn't send to the DR5000 until Traintastic is in *RUN* state.

**Comment by reinder** [comment]
Closed, no response for 10 months, please reopen if it is still relevant.
